import type { ParticipantMap, Room } from "./types";

export const ownerParticipantId = "owner";

export const demoParticipants: ParticipantMap = {
  owner: {
    id: ownerParticipantId,
    canonicalName: "Owner",
    displayName: "Owner",
    identityBadge: "Owner",
    serviceLabel: "Owner",
    kind: "human",
    initials: "O",
    accent: "#d87561",
  },
  "claude-web": {
    id: "claude-web",
    canonicalName: "Claude Web",
    displayName: "Claude Web",
    identityBadge: "CW",
    serviceLabel: "Browser adapter",
    kind: "ai",
    initials: "C",
    accent: "#cc785c",
  },
  "claude-code": {
    id: "claude-code",
    canonicalName: "Claude Fable",
    displayName: "Claude Fable",
    identityBadge: "Fable",
    serviceLabel: "Claude Code · Fable 5",
    kind: "ai",
    initials: "CC",
    accent: "#a85f48",
  },
  codex: {
    id: "codex",
    canonicalName: "Codex",
    displayName: "Codex",
    identityBadge: "CX",
    serviceLabel: "Coding agent",
    kind: "ai",
    initials: "CX",
    accent: "#198754",
  },
  chatgpt: {
    id: "chatgpt",
    canonicalName: "ChatGPT",
    displayName: "ChatGPT",
    identityBadge: "GPT",
    serviceLabel: "Web adapter",
    kind: "ai",
    initials: "G",
    accent: "#10a37f",
  },
  grok: {
    id: "grok",
    canonicalName: "Grok",
    displayName: "Grok",
    identityBadge: "G",
    serviceLabel: "CLI chat adapter",
    kind: "ai",
    initials: "X",
    accent: "#242424",
  },
  gemini: {
    id: "gemini",
    canonicalName: "Gemini",
    displayName: "Gemini",
    identityBadge: "GM",
    serviceLabel: "Antigravity CLI",
    kind: "ai",
    initials: "✦",
    accent: "#5b71ea",
  },
  "openai-api": {
    id: "openai-api",
    canonicalName: "OpenAI API",
    displayName: "OpenAI API",
    identityBadge: "OA",
    serviceLabel: "API adapter",
    kind: "ai",
    initials: "OA",
    accent: "#006f5f",
  },
  "generic-mcp": {
    id: "generic-mcp",
    canonicalName: "Generic MCP",
    displayName: "Generic MCP",
    identityBadge: "MCP",
    serviceLabel: "MCP adapter",
    kind: "ai",
    initials: "M",
    accent: "#7c4dba",
  },
  other: {
    id: "other",
    canonicalName: "Custom AI",
    displayName: "その他",
    identityBadge: "AI",
    serviceLabel: "Custom adapter",
    kind: "ai",
    initials: "+",
    accent: "#6b7280",
  },
};

export const initialRooms: Room[] = [
  {
    id: "moe-dev-room",
    name: "M.I.O.開発室",
    participantIds: [ownerParticipantId, "claude-web", "codex", "gemini"],
    updatedLabel: "いま",
    messages: [
      {
        id: "welcome-1",
        authorId: ownerParticipantId,
        body: "みんな、M.I.O.のトークルームUIを作っていきましょうー。",
        targetIds: ["claude-web", "codex", "gemini"],
        sentAt: "19:42",
      },
      {
        id: "welcome-2",
        authorId: "codex",
        body: "了解です。ルーム参加者と、メッセージごとの宛先を分けておきますね。",
        targetIds: [ownerParticipantId],
        sentAt: "19:42",
        isDemo: true,
      },
      {
        id: "welcome-3",
        authorId: "claude-web",
        body: "背景やアイコンを自分好みにできる余白も、最初から確保しておきます。",
        targetIds: [ownerParticipantId],
        sentAt: "19:43",
        isDemo: true,
      },
    ],
  },
  {
    id: "comparison-room",
    name: "回答くらべ部屋",
    participantIds: [ownerParticipantId, "chatgpt", "grok", "gemini"],
    updatedLabel: "12分前",
    messages: [
      {
        id: "comparison-1",
        authorId: ownerParticipantId,
        body: "同じ質問を三人に投げて、違いを見てみたい。",
        targetIds: ["chatgpt", "grok", "gemini"],
        sentAt: "19:30",
      },
    ],
  },
  {
    id: "mcp-lab",
    name: "MCP実験室",
    participantIds: [ownerParticipantId, "generic-mcp", "openai-api"],
    updatedLabel: "昨日",
    messages: [],
  },
];

export const initialRecipientIds = ["codex"];
